/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SchoolUniformsRouteImport } from './routes/school-uniforms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories.index'
import { Route as AccessoriesSlugRouteImport } from './routes/accessories.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccessoriesRouteImport } from './routes/admin.accessories'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminMedicalRouteImport } from './routes/admin.medical'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductMappingRouteImport } from './routes/admin.product-mapping'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSchoolUniformRouteImport } from './routes/admin.school-uniform'
import { Route as AdminWebsiteSettingRouteImport } from './routes/admin.website-setting'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminAccessoriesIndexRouteImport } from './routes/admin.accessories.index'
import { Route as AdminAccessoriesCategoryIdRouteImport } from './routes/admin.accessories.$categoryId'
import { Route as AdminCollegesIndexRouteImport } from './routes/admin.colleges.index'
import { Route as AdminCollegesSlugRouteImport } from './routes/admin.colleges.$slug'
import { Route as AdminProductMappingIndexRouteImport } from './routes/admin.product-mapping.index'
import { Route as AdminProductMappingDeliveryChargesRouteImport } from './routes/admin.product-mapping.delivery-charges'
import { Route as AdminProductMappingSizingRouteImport } from './routes/admin.product-mapping.sizing'
import { Route as AdminSchoolUniformIndexRouteImport } from './routes/admin.school-uniform.index'
import { Route as AdminSchoolUniformSlugRouteImport } from './routes/admin.school-uniform.$slug'
import { Route as AdminWebsiteSettingIndexRouteImport } from './routes/admin.website-setting.index'
import { Route as AdminWebsiteSettingAdvertisementsRouteImport } from './routes/admin.website-setting.advertisements'
import { Route as AdminWebsiteSettingBankAccountsRouteImport } from './routes/admin.website-setting.bank-accounts'
import { Route as AdminWebsiteSettingBusinessInformationRouteImport } from './routes/admin.website-setting.business-information'
import { Route as ProductAccessoriesIdRouteImport } from './routes/product.accessories.$id'
import { Route as ProductCollegeIdRouteImport } from './routes/product.college.$id'
import { Route as ProductMedicalIdRouteImport } from './routes/product.medical.$id'
import { Route as ProductSchoolIdRouteImport } from './routes/product.school.$id'
import { Route as AdminCollegesSlugIndexRouteImport } from './routes/admin.colleges.$slug.index'
import { Route as AdminCollegesSlugCollectionRouteImport } from './routes/admin.colleges.$slug.$collection'
import { Route as AdminCollegesSlugProductsRouteImport } from './routes/admin.colleges.$slug.products'
import { Route as AdminCollegesSlugStructureRouteImport } from './routes/admin.colleges.$slug.structure'
import { Route as AdminProductMappingSizingIndexRouteImport } from './routes/admin.product-mapping.sizing.index'
import { Route as AdminProductMappingSizingIdRouteImport } from './routes/admin.product-mapping.sizing.$id'
import { Route as AdminSchoolUniformSlugIndexRouteImport } from './routes/admin.school-uniform.$slug.index'
import { Route as AdminSchoolUniformSlugCollectionRouteImport } from './routes/admin.school-uniform.$slug.$collection'
import { Route as AdminSchoolUniformSlugProductsRouteImport } from './routes/admin.school-uniform.$slug.products'
import { Route as AdminSchoolUniformSlugStructureRouteImport } from './routes/admin.school-uniform.$slug.structure'
import { Route as AdminCollegesSlugCollectionIndexRouteImport } from './routes/admin.colleges.$slug.$collection.index'
import { Route as AdminCollegesSlugCollectionCategoryIdRouteImport } from './routes/admin.colleges.$slug.$collection.$categoryId'
import { Route as AdminSchoolUniformSlugCollectionIndexRouteImport } from './routes/admin.school-uniform.$slug.$collection.index'
import { Route as AdminSchoolUniformSlugCollectionCategoryIdRouteImport } from './routes/admin.school-uniform.$slug.$collection.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolUniformsRoute = SchoolUniformsRouteImport.update({
  id: '/school-uniforms',
  path: '/school-uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccessoriesRoute,
} as any)
const AccessoriesSlugRoute = AccessoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AccessoriesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessoriesRoute = AdminAccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicalRoute = AdminMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductMappingRoute = AdminProductMappingRouteImport.update({
  id: '/product-mapping',
  path: '/product-mapping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolUniformRoute = AdminSchoolUniformRouteImport.update({
  id: '/school-uniform',
  path: '/school-uniform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSettingRoute = AdminWebsiteSettingRouteImport.update({
  id: '/website-setting',
  path: '/website-setting',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminAccessoriesIndexRoute = AdminAccessoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAccessoriesRoute,
} as any)
const AdminAccessoriesCategoryIdRoute =
  AdminAccessoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminAccessoriesRoute,
  } as any)
const AdminCollegesIndexRoute = AdminCollegesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCollegesRoute,
} as any)
const AdminCollegesSlugRoute = AdminCollegesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCollegesRoute,
} as any)
const AdminProductMappingIndexRoute =
  AdminProductMappingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProductMappingRoute,
  } as any)
const AdminProductMappingDeliveryChargesRoute =
  AdminProductMappingDeliveryChargesRouteImport.update({
    id: '/delivery-charges',
    path: '/delivery-charges',
    getParentRoute: () => AdminProductMappingRoute,
  } as any)
const AdminProductMappingSizingRoute =
  AdminProductMappingSizingRouteImport.update({
    id: '/sizing',
    path: '/sizing',
    getParentRoute: () => AdminProductMappingRoute,
  } as any)
const AdminSchoolUniformIndexRoute = AdminSchoolUniformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSchoolUniformRoute,
} as any)
const AdminSchoolUniformSlugRoute = AdminSchoolUniformSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminSchoolUniformRoute,
} as any)
const AdminWebsiteSettingIndexRoute =
  AdminWebsiteSettingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWebsiteSettingRoute,
  } as any)
const AdminWebsiteSettingAdvertisementsRoute =
  AdminWebsiteSettingAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => AdminWebsiteSettingRoute,
  } as any)
const AdminWebsiteSettingBankAccountsRoute =
  AdminWebsiteSettingBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AdminWebsiteSettingRoute,
  } as any)
const AdminWebsiteSettingBusinessInformationRoute =
  AdminWebsiteSettingBusinessInformationRouteImport.update({
    id: '/business-information',
    path: '/business-information',
    getParentRoute: () => AdminWebsiteSettingRoute,
  } as any)
const ProductAccessoriesIdRoute = ProductAccessoriesIdRouteImport.update({
  id: '/product/accessories/$id',
  path: '/product/accessories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCollegeIdRoute = ProductCollegeIdRouteImport.update({
  id: '/product/college/$id',
  path: '/product/college/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMedicalIdRoute = ProductMedicalIdRouteImport.update({
  id: '/product/medical/$id',
  path: '/product/medical/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSchoolIdRoute = ProductSchoolIdRouteImport.update({
  id: '/product/school/$id',
  path: '/product/school/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollegesSlugIndexRoute = AdminCollegesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCollegesSlugRoute,
} as any)
const AdminCollegesSlugCollectionRoute =
  AdminCollegesSlugCollectionRouteImport.update({
    id: '/$collection',
    path: '/$collection',
    getParentRoute: () => AdminCollegesSlugRoute,
  } as any)
const AdminCollegesSlugProductsRoute =
  AdminCollegesSlugProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminCollegesSlugRoute,
  } as any)
const AdminCollegesSlugStructureRoute =
  AdminCollegesSlugStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AdminCollegesSlugRoute,
  } as any)
const AdminProductMappingSizingIndexRoute =
  AdminProductMappingSizingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProductMappingSizingRoute,
  } as any)
const AdminProductMappingSizingIdRoute =
  AdminProductMappingSizingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminProductMappingSizingRoute,
  } as any)
const AdminSchoolUniformSlugIndexRoute =
  AdminSchoolUniformSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSchoolUniformSlugRoute,
  } as any)
const AdminSchoolUniformSlugCollectionRoute =
  AdminSchoolUniformSlugCollectionRouteImport.update({
    id: '/$collection',
    path: '/$collection',
    getParentRoute: () => AdminSchoolUniformSlugRoute,
  } as any)
const AdminSchoolUniformSlugProductsRoute =
  AdminSchoolUniformSlugProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminSchoolUniformSlugRoute,
  } as any)
const AdminSchoolUniformSlugStructureRoute =
  AdminSchoolUniformSlugStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AdminSchoolUniformSlugRoute,
  } as any)
const AdminCollegesSlugCollectionIndexRoute =
  AdminCollegesSlugCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCollegesSlugCollectionRoute,
  } as any)
const AdminCollegesSlugCollectionCategoryIdRoute =
  AdminCollegesSlugCollectionCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminCollegesSlugCollectionRoute,
  } as any)
const AdminSchoolUniformSlugCollectionIndexRoute =
  AdminSchoolUniformSlugCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSchoolUniformSlugCollectionRoute,
  } as any)
const AdminSchoolUniformSlugCollectionCategoryIdRoute =
  AdminSchoolUniformSlugCollectionCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminSchoolUniformSlugCollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/medical': typeof MedicalRoute
  '/orders': typeof OrdersRouteWithChildren
  '/school-uniforms': typeof SchoolUniformsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/admin/accessories': typeof AdminAccessoriesRouteWithChildren
  '/admin/colleges': typeof AdminCollegesRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product-mapping': typeof AdminProductMappingRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/school-uniform': typeof AdminSchoolUniformRouteWithChildren
  '/admin/website-setting': typeof AdminWebsiteSettingRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/accessories/$categoryId': typeof AdminAccessoriesCategoryIdRoute
  '/admin/colleges/$slug': typeof AdminCollegesSlugRouteWithChildren
  '/admin/product-mapping/delivery-charges': typeof AdminProductMappingDeliveryChargesRoute
  '/admin/product-mapping/sizing': typeof AdminProductMappingSizingRouteWithChildren
  '/admin/school-uniform/$slug': typeof AdminSchoolUniformSlugRouteWithChildren
  '/admin/website-setting/advertisements': typeof AdminWebsiteSettingAdvertisementsRoute
  '/admin/website-setting/bank-accounts': typeof AdminWebsiteSettingBankAccountsRoute
  '/admin/website-setting/business-information': typeof AdminWebsiteSettingBusinessInformationRoute
  '/product/accessories/$id': typeof ProductAccessoriesIdRoute
  '/product/college/$id': typeof ProductCollegeIdRoute
  '/product/medical/$id': typeof ProductMedicalIdRoute
  '/product/school/$id': typeof ProductSchoolIdRoute
  '/admin/accessories/': typeof AdminAccessoriesIndexRoute
  '/admin/colleges/': typeof AdminCollegesIndexRoute
  '/admin/product-mapping/': typeof AdminProductMappingIndexRoute
  '/admin/school-uniform/': typeof AdminSchoolUniformIndexRoute
  '/admin/website-setting/': typeof AdminWebsiteSettingIndexRoute
  '/admin/colleges/$slug/$collection': typeof AdminCollegesSlugCollectionRouteWithChildren
  '/admin/colleges/$slug/products': typeof AdminCollegesSlugProductsRoute
  '/admin/colleges/$slug/structure': typeof AdminCollegesSlugStructureRoute
  '/admin/product-mapping/sizing/$id': typeof AdminProductMappingSizingIdRoute
  '/admin/school-uniform/$slug/$collection': typeof AdminSchoolUniformSlugCollectionRouteWithChildren
  '/admin/school-uniform/$slug/products': typeof AdminSchoolUniformSlugProductsRoute
  '/admin/school-uniform/$slug/structure': typeof AdminSchoolUniformSlugStructureRoute
  '/admin/colleges/$slug/': typeof AdminCollegesSlugIndexRoute
  '/admin/product-mapping/sizing/': typeof AdminProductMappingSizingIndexRoute
  '/admin/school-uniform/$slug/': typeof AdminSchoolUniformSlugIndexRoute
  '/admin/colleges/$slug/$collection/$categoryId': typeof AdminCollegesSlugCollectionCategoryIdRoute
  '/admin/school-uniform/$slug/$collection/$categoryId': typeof AdminSchoolUniformSlugCollectionCategoryIdRoute
  '/admin/colleges/$slug/$collection/': typeof AdminCollegesSlugCollectionIndexRoute
  '/admin/school-uniform/$slug/$collection/': typeof AdminSchoolUniformSlugCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/medical': typeof MedicalRoute
  '/orders': typeof OrdersRouteWithChildren
  '/school-uniforms': typeof SchoolUniformsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accessories/$categoryId': typeof AdminAccessoriesCategoryIdRoute
  '/admin/product-mapping/delivery-charges': typeof AdminProductMappingDeliveryChargesRoute
  '/admin/website-setting/advertisements': typeof AdminWebsiteSettingAdvertisementsRoute
  '/admin/website-setting/bank-accounts': typeof AdminWebsiteSettingBankAccountsRoute
  '/admin/website-setting/business-information': typeof AdminWebsiteSettingBusinessInformationRoute
  '/product/accessories/$id': typeof ProductAccessoriesIdRoute
  '/product/college/$id': typeof ProductCollegeIdRoute
  '/product/medical/$id': typeof ProductMedicalIdRoute
  '/product/school/$id': typeof ProductSchoolIdRoute
  '/admin/accessories': typeof AdminAccessoriesIndexRoute
  '/admin/colleges': typeof AdminCollegesIndexRoute
  '/admin/product-mapping': typeof AdminProductMappingIndexRoute
  '/admin/school-uniform': typeof AdminSchoolUniformIndexRoute
  '/admin/website-setting': typeof AdminWebsiteSettingIndexRoute
  '/admin/colleges/$slug/products': typeof AdminCollegesSlugProductsRoute
  '/admin/colleges/$slug/structure': typeof AdminCollegesSlugStructureRoute
  '/admin/product-mapping/sizing/$id': typeof AdminProductMappingSizingIdRoute
  '/admin/school-uniform/$slug/products': typeof AdminSchoolUniformSlugProductsRoute
  '/admin/school-uniform/$slug/structure': typeof AdminSchoolUniformSlugStructureRoute
  '/admin/colleges/$slug': typeof AdminCollegesSlugIndexRoute
  '/admin/product-mapping/sizing': typeof AdminProductMappingSizingIndexRoute
  '/admin/school-uniform/$slug': typeof AdminSchoolUniformSlugIndexRoute
  '/admin/colleges/$slug/$collection/$categoryId': typeof AdminCollegesSlugCollectionCategoryIdRoute
  '/admin/school-uniform/$slug/$collection/$categoryId': typeof AdminSchoolUniformSlugCollectionCategoryIdRoute
  '/admin/colleges/$slug/$collection': typeof AdminCollegesSlugCollectionIndexRoute
  '/admin/school-uniform/$slug/$collection': typeof AdminSchoolUniformSlugCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/medical': typeof MedicalRoute
  '/orders': typeof OrdersRouteWithChildren
  '/school-uniforms': typeof SchoolUniformsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/admin/accessories': typeof AdminAccessoriesRouteWithChildren
  '/admin/colleges': typeof AdminCollegesRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product-mapping': typeof AdminProductMappingRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/school-uniform': typeof AdminSchoolUniformRouteWithChildren
  '/admin/website-setting': typeof AdminWebsiteSettingRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/accessories/$categoryId': typeof AdminAccessoriesCategoryIdRoute
  '/admin/colleges/$slug': typeof AdminCollegesSlugRouteWithChildren
  '/admin/product-mapping/delivery-charges': typeof AdminProductMappingDeliveryChargesRoute
  '/admin/product-mapping/sizing': typeof AdminProductMappingSizingRouteWithChildren
  '/admin/school-uniform/$slug': typeof AdminSchoolUniformSlugRouteWithChildren
  '/admin/website-setting/advertisements': typeof AdminWebsiteSettingAdvertisementsRoute
  '/admin/website-setting/bank-accounts': typeof AdminWebsiteSettingBankAccountsRoute
  '/admin/website-setting/business-information': typeof AdminWebsiteSettingBusinessInformationRoute
  '/product/accessories/$id': typeof ProductAccessoriesIdRoute
  '/product/college/$id': typeof ProductCollegeIdRoute
  '/product/medical/$id': typeof ProductMedicalIdRoute
  '/product/school/$id': typeof ProductSchoolIdRoute
  '/admin/accessories/': typeof AdminAccessoriesIndexRoute
  '/admin/colleges/': typeof AdminCollegesIndexRoute
  '/admin/product-mapping/': typeof AdminProductMappingIndexRoute
  '/admin/school-uniform/': typeof AdminSchoolUniformIndexRoute
  '/admin/website-setting/': typeof AdminWebsiteSettingIndexRoute
  '/admin/colleges/$slug/$collection': typeof AdminCollegesSlugCollectionRouteWithChildren
  '/admin/colleges/$slug/products': typeof AdminCollegesSlugProductsRoute
  '/admin/colleges/$slug/structure': typeof AdminCollegesSlugStructureRoute
  '/admin/product-mapping/sizing/$id': typeof AdminProductMappingSizingIdRoute
  '/admin/school-uniform/$slug/$collection': typeof AdminSchoolUniformSlugCollectionRouteWithChildren
  '/admin/school-uniform/$slug/products': typeof AdminSchoolUniformSlugProductsRoute
  '/admin/school-uniform/$slug/structure': typeof AdminSchoolUniformSlugStructureRoute
  '/admin/colleges/$slug/': typeof AdminCollegesSlugIndexRoute
  '/admin/product-mapping/sizing/': typeof AdminProductMappingSizingIndexRoute
  '/admin/school-uniform/$slug/': typeof AdminSchoolUniformSlugIndexRoute
  '/admin/colleges/$slug/$collection/$categoryId': typeof AdminCollegesSlugCollectionCategoryIdRoute
  '/admin/school-uniform/$slug/$collection/$categoryId': typeof AdminSchoolUniformSlugCollectionCategoryIdRoute
  '/admin/colleges/$slug/$collection/': typeof AdminCollegesSlugCollectionIndexRoute
  '/admin/school-uniform/$slug/$collection/': typeof AdminSchoolUniformSlugCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/colleges'
    | '/contact'
    | '/medical'
    | '/orders'
    | '/school-uniforms'
    | '/sitemap.xml'
    | '/wishlist'
    | '/accessories/$slug'
    | '/admin/accessories'
    | '/admin/colleges'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/medical'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/product-mapping'
    | '/admin/reviews'
    | '/admin/school-uniform'
    | '/admin/website-setting'
    | '/orders/$id'
    | '/accessories/'
    | '/admin/'
    | '/admin/accessories/$categoryId'
    | '/admin/colleges/$slug'
    | '/admin/product-mapping/delivery-charges'
    | '/admin/product-mapping/sizing'
    | '/admin/school-uniform/$slug'
    | '/admin/website-setting/advertisements'
    | '/admin/website-setting/bank-accounts'
    | '/admin/website-setting/business-information'
    | '/product/accessories/$id'
    | '/product/college/$id'
    | '/product/medical/$id'
    | '/product/school/$id'
    | '/admin/accessories/'
    | '/admin/colleges/'
    | '/admin/product-mapping/'
    | '/admin/school-uniform/'
    | '/admin/website-setting/'
    | '/admin/colleges/$slug/$collection'
    | '/admin/colleges/$slug/products'
    | '/admin/colleges/$slug/structure'
    | '/admin/product-mapping/sizing/$id'
    | '/admin/school-uniform/$slug/$collection'
    | '/admin/school-uniform/$slug/products'
    | '/admin/school-uniform/$slug/structure'
    | '/admin/colleges/$slug/'
    | '/admin/product-mapping/sizing/'
    | '/admin/school-uniform/$slug/'
    | '/admin/colleges/$slug/$collection/$categoryId'
    | '/admin/school-uniform/$slug/$collection/$categoryId'
    | '/admin/colleges/$slug/$collection/'
    | '/admin/school-uniform/$slug/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/colleges'
    | '/contact'
    | '/medical'
    | '/orders'
    | '/school-uniforms'
    | '/sitemap.xml'
    | '/wishlist'
    | '/accessories/$slug'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/medical'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/reviews'
    | '/orders/$id'
    | '/accessories'
    | '/admin'
    | '/admin/accessories/$categoryId'
    | '/admin/product-mapping/delivery-charges'
    | '/admin/website-setting/advertisements'
    | '/admin/website-setting/bank-accounts'
    | '/admin/website-setting/business-information'
    | '/product/accessories/$id'
    | '/product/college/$id'
    | '/product/medical/$id'
    | '/product/school/$id'
    | '/admin/accessories'
    | '/admin/colleges'
    | '/admin/product-mapping'
    | '/admin/school-uniform'
    | '/admin/website-setting'
    | '/admin/colleges/$slug/products'
    | '/admin/colleges/$slug/structure'
    | '/admin/product-mapping/sizing/$id'
    | '/admin/school-uniform/$slug/products'
    | '/admin/school-uniform/$slug/structure'
    | '/admin/colleges/$slug'
    | '/admin/product-mapping/sizing'
    | '/admin/school-uniform/$slug'
    | '/admin/colleges/$slug/$collection/$categoryId'
    | '/admin/school-uniform/$slug/$collection/$categoryId'
    | '/admin/colleges/$slug/$collection'
    | '/admin/school-uniform/$slug/$collection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/colleges'
    | '/contact'
    | '/medical'
    | '/orders'
    | '/school-uniforms'
    | '/sitemap.xml'
    | '/wishlist'
    | '/accessories/$slug'
    | '/admin/accessories'
    | '/admin/colleges'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/medical'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/product-mapping'
    | '/admin/reviews'
    | '/admin/school-uniform'
    | '/admin/website-setting'
    | '/orders/$id'
    | '/accessories/'
    | '/admin/'
    | '/admin/accessories/$categoryId'
    | '/admin/colleges/$slug'
    | '/admin/product-mapping/delivery-charges'
    | '/admin/product-mapping/sizing'
    | '/admin/school-uniform/$slug'
    | '/admin/website-setting/advertisements'
    | '/admin/website-setting/bank-accounts'
    | '/admin/website-setting/business-information'
    | '/product/accessories/$id'
    | '/product/college/$id'
    | '/product/medical/$id'
    | '/product/school/$id'
    | '/admin/accessories/'
    | '/admin/colleges/'
    | '/admin/product-mapping/'
    | '/admin/school-uniform/'
    | '/admin/website-setting/'
    | '/admin/colleges/$slug/$collection'
    | '/admin/colleges/$slug/products'
    | '/admin/colleges/$slug/structure'
    | '/admin/product-mapping/sizing/$id'
    | '/admin/school-uniform/$slug/$collection'
    | '/admin/school-uniform/$slug/products'
    | '/admin/school-uniform/$slug/structure'
    | '/admin/colleges/$slug/'
    | '/admin/product-mapping/sizing/'
    | '/admin/school-uniform/$slug/'
    | '/admin/colleges/$slug/$collection/$categoryId'
    | '/admin/school-uniform/$slug/$collection/$categoryId'
    | '/admin/colleges/$slug/$collection/'
    | '/admin/school-uniform/$slug/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollegesRoute: typeof CollegesRoute
  ContactRoute: typeof ContactRoute
  MedicalRoute: typeof MedicalRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  SchoolUniformsRoute: typeof SchoolUniformsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  ProductAccessoriesIdRoute: typeof ProductAccessoriesIdRoute
  ProductCollegeIdRoute: typeof ProductCollegeIdRoute
  ProductMedicalIdRoute: typeof ProductMedicalIdRoute
  ProductSchoolIdRoute: typeof ProductSchoolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-uniforms': {
      id: '/school-uniforms'
      path: '/school-uniforms'
      fullPath: '/school-uniforms'
      preLoaderRoute: typeof SchoolUniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/accessories/$slug': {
      id: '/accessories/$slug'
      path: '/$slug'
      fullPath: '/accessories/$slug'
      preLoaderRoute: typeof AccessoriesSlugRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accessories': {
      id: '/admin/accessories'
      path: '/accessories'
      fullPath: '/admin/accessories'
      preLoaderRoute: typeof AdminAccessoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medical': {
      id: '/admin/medical'
      path: '/medical'
      fullPath: '/admin/medical'
      preLoaderRoute: typeof AdminMedicalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-mapping': {
      id: '/admin/product-mapping'
      path: '/product-mapping'
      fullPath: '/admin/product-mapping'
      preLoaderRoute: typeof AdminProductMappingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/school-uniform': {
      id: '/admin/school-uniform'
      path: '/school-uniform'
      fullPath: '/admin/school-uniform'
      preLoaderRoute: typeof AdminSchoolUniformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website-setting': {
      id: '/admin/website-setting'
      path: '/website-setting'
      fullPath: '/admin/website-setting'
      preLoaderRoute: typeof AdminWebsiteSettingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/accessories/': {
      id: '/admin/accessories/'
      path: '/'
      fullPath: '/admin/accessories/'
      preLoaderRoute: typeof AdminAccessoriesIndexRouteImport
      parentRoute: typeof AdminAccessoriesRoute
    }
    '/admin/accessories/$categoryId': {
      id: '/admin/accessories/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/accessories/$categoryId'
      preLoaderRoute: typeof AdminAccessoriesCategoryIdRouteImport
      parentRoute: typeof AdminAccessoriesRoute
    }
    '/admin/colleges/': {
      id: '/admin/colleges/'
      path: '/'
      fullPath: '/admin/colleges/'
      preLoaderRoute: typeof AdminCollegesIndexRouteImport
      parentRoute: typeof AdminCollegesRoute
    }
    '/admin/colleges/$slug': {
      id: '/admin/colleges/$slug'
      path: '/$slug'
      fullPath: '/admin/colleges/$slug'
      preLoaderRoute: typeof AdminCollegesSlugRouteImport
      parentRoute: typeof AdminCollegesRoute
    }
    '/admin/product-mapping/': {
      id: '/admin/product-mapping/'
      path: '/'
      fullPath: '/admin/product-mapping/'
      preLoaderRoute: typeof AdminProductMappingIndexRouteImport
      parentRoute: typeof AdminProductMappingRoute
    }
    '/admin/product-mapping/delivery-charges': {
      id: '/admin/product-mapping/delivery-charges'
      path: '/delivery-charges'
      fullPath: '/admin/product-mapping/delivery-charges'
      preLoaderRoute: typeof AdminProductMappingDeliveryChargesRouteImport
      parentRoute: typeof AdminProductMappingRoute
    }
    '/admin/product-mapping/sizing': {
      id: '/admin/product-mapping/sizing'
      path: '/sizing'
      fullPath: '/admin/product-mapping/sizing'
      preLoaderRoute: typeof AdminProductMappingSizingRouteImport
      parentRoute: typeof AdminProductMappingRoute
    }
    '/admin/school-uniform/': {
      id: '/admin/school-uniform/'
      path: '/'
      fullPath: '/admin/school-uniform/'
      preLoaderRoute: typeof AdminSchoolUniformIndexRouteImport
      parentRoute: typeof AdminSchoolUniformRoute
    }
    '/admin/school-uniform/$slug': {
      id: '/admin/school-uniform/$slug'
      path: '/$slug'
      fullPath: '/admin/school-uniform/$slug'
      preLoaderRoute: typeof AdminSchoolUniformSlugRouteImport
      parentRoute: typeof AdminSchoolUniformRoute
    }
    '/admin/website-setting/': {
      id: '/admin/website-setting/'
      path: '/'
      fullPath: '/admin/website-setting/'
      preLoaderRoute: typeof AdminWebsiteSettingIndexRouteImport
      parentRoute: typeof AdminWebsiteSettingRoute
    }
    '/admin/website-setting/advertisements': {
      id: '/admin/website-setting/advertisements'
      path: '/advertisements'
      fullPath: '/admin/website-setting/advertisements'
      preLoaderRoute: typeof AdminWebsiteSettingAdvertisementsRouteImport
      parentRoute: typeof AdminWebsiteSettingRoute
    }
    '/admin/website-setting/bank-accounts': {
      id: '/admin/website-setting/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/admin/website-setting/bank-accounts'
      preLoaderRoute: typeof AdminWebsiteSettingBankAccountsRouteImport
      parentRoute: typeof AdminWebsiteSettingRoute
    }
    '/admin/website-setting/business-information': {
      id: '/admin/website-setting/business-information'
      path: '/business-information'
      fullPath: '/admin/website-setting/business-information'
      preLoaderRoute: typeof AdminWebsiteSettingBusinessInformationRouteImport
      parentRoute: typeof AdminWebsiteSettingRoute
    }
    '/product/accessories/$id': {
      id: '/product/accessories/$id'
      path: '/product/accessories/$id'
      fullPath: '/product/accessories/$id'
      preLoaderRoute: typeof ProductAccessoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/college/$id': {
      id: '/product/college/$id'
      path: '/product/college/$id'
      fullPath: '/product/college/$id'
      preLoaderRoute: typeof ProductCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/medical/$id': {
      id: '/product/medical/$id'
      path: '/product/medical/$id'
      fullPath: '/product/medical/$id'
      preLoaderRoute: typeof ProductMedicalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/school/$id': {
      id: '/product/school/$id'
      path: '/product/school/$id'
      fullPath: '/product/school/$id'
      preLoaderRoute: typeof ProductSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/colleges/$slug/': {
      id: '/admin/colleges/$slug/'
      path: '/'
      fullPath: '/admin/colleges/$slug/'
      preLoaderRoute: typeof AdminCollegesSlugIndexRouteImport
      parentRoute: typeof AdminCollegesSlugRoute
    }
    '/admin/colleges/$slug/$collection': {
      id: '/admin/colleges/$slug/$collection'
      path: '/$collection'
      fullPath: '/admin/colleges/$slug/$collection'
      preLoaderRoute: typeof AdminCollegesSlugCollectionRouteImport
      parentRoute: typeof AdminCollegesSlugRoute
    }
    '/admin/colleges/$slug/products': {
      id: '/admin/colleges/$slug/products'
      path: '/products'
      fullPath: '/admin/colleges/$slug/products'
      preLoaderRoute: typeof AdminCollegesSlugProductsRouteImport
      parentRoute: typeof AdminCollegesSlugRoute
    }
    '/admin/colleges/$slug/structure': {
      id: '/admin/colleges/$slug/structure'
      path: '/structure'
      fullPath: '/admin/colleges/$slug/structure'
      preLoaderRoute: typeof AdminCollegesSlugStructureRouteImport
      parentRoute: typeof AdminCollegesSlugRoute
    }
    '/admin/product-mapping/sizing/': {
      id: '/admin/product-mapping/sizing/'
      path: '/'
      fullPath: '/admin/product-mapping/sizing/'
      preLoaderRoute: typeof AdminProductMappingSizingIndexRouteImport
      parentRoute: typeof AdminProductMappingSizingRoute
    }
    '/admin/product-mapping/sizing/$id': {
      id: '/admin/product-mapping/sizing/$id'
      path: '/$id'
      fullPath: '/admin/product-mapping/sizing/$id'
      preLoaderRoute: typeof AdminProductMappingSizingIdRouteImport
      parentRoute: typeof AdminProductMappingSizingRoute
    }
    '/admin/school-uniform/$slug/': {
      id: '/admin/school-uniform/$slug/'
      path: '/'
      fullPath: '/admin/school-uniform/$slug/'
      preLoaderRoute: typeof AdminSchoolUniformSlugIndexRouteImport
      parentRoute: typeof AdminSchoolUniformSlugRoute
    }
    '/admin/school-uniform/$slug/$collection': {
      id: '/admin/school-uniform/$slug/$collection'
      path: '/$collection'
      fullPath: '/admin/school-uniform/$slug/$collection'
      preLoaderRoute: typeof AdminSchoolUniformSlugCollectionRouteImport
      parentRoute: typeof AdminSchoolUniformSlugRoute
    }
    '/admin/school-uniform/$slug/products': {
      id: '/admin/school-uniform/$slug/products'
      path: '/products'
      fullPath: '/admin/school-uniform/$slug/products'
      preLoaderRoute: typeof AdminSchoolUniformSlugProductsRouteImport
      parentRoute: typeof AdminSchoolUniformSlugRoute
    }
    '/admin/school-uniform/$slug/structure': {
      id: '/admin/school-uniform/$slug/structure'
      path: '/structure'
      fullPath: '/admin/school-uniform/$slug/structure'
      preLoaderRoute: typeof AdminSchoolUniformSlugStructureRouteImport
      parentRoute: typeof AdminSchoolUniformSlugRoute
    }
    '/admin/colleges/$slug/$collection/': {
      id: '/admin/colleges/$slug/$collection/'
      path: '/'
      fullPath: '/admin/colleges/$slug/$collection/'
      preLoaderRoute: typeof AdminCollegesSlugCollectionIndexRouteImport
      parentRoute: typeof AdminCollegesSlugCollectionRoute
    }
    '/admin/colleges/$slug/$collection/$categoryId': {
      id: '/admin/colleges/$slug/$collection/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/colleges/$slug/$collection/$categoryId'
      preLoaderRoute: typeof AdminCollegesSlugCollectionCategoryIdRouteImport
      parentRoute: typeof AdminCollegesSlugCollectionRoute
    }
    '/admin/school-uniform/$slug/$collection/': {
      id: '/admin/school-uniform/$slug/$collection/'
      path: '/'
      fullPath: '/admin/school-uniform/$slug/$collection/'
      preLoaderRoute: typeof AdminSchoolUniformSlugCollectionIndexRouteImport
      parentRoute: typeof AdminSchoolUniformSlugCollectionRoute
    }
    '/admin/school-uniform/$slug/$collection/$categoryId': {
      id: '/admin/school-uniform/$slug/$collection/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/school-uniform/$slug/$collection/$categoryId'
      preLoaderRoute: typeof AdminSchoolUniformSlugCollectionCategoryIdRouteImport
      parentRoute: typeof AdminSchoolUniformSlugCollectionRoute
    }
  }
}

interface AccessoriesRouteChildren {
  AccessoriesSlugRoute: typeof AccessoriesSlugRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesSlugRoute: AccessoriesSlugRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface AdminAccessoriesRouteChildren {
  AdminAccessoriesCategoryIdRoute: typeof AdminAccessoriesCategoryIdRoute
  AdminAccessoriesIndexRoute: typeof AdminAccessoriesIndexRoute
}

const AdminAccessoriesRouteChildren: AdminAccessoriesRouteChildren = {
  AdminAccessoriesCategoryIdRoute: AdminAccessoriesCategoryIdRoute,
  AdminAccessoriesIndexRoute: AdminAccessoriesIndexRoute,
}

const AdminAccessoriesRouteWithChildren =
  AdminAccessoriesRoute._addFileChildren(AdminAccessoriesRouteChildren)

interface AdminCollegesSlugCollectionRouteChildren {
  AdminCollegesSlugCollectionCategoryIdRoute: typeof AdminCollegesSlugCollectionCategoryIdRoute
  AdminCollegesSlugCollectionIndexRoute: typeof AdminCollegesSlugCollectionIndexRoute
}

const AdminCollegesSlugCollectionRouteChildren: AdminCollegesSlugCollectionRouteChildren =
  {
    AdminCollegesSlugCollectionCategoryIdRoute:
      AdminCollegesSlugCollectionCategoryIdRoute,
    AdminCollegesSlugCollectionIndexRoute:
      AdminCollegesSlugCollectionIndexRoute,
  }

const AdminCollegesSlugCollectionRouteWithChildren =
  AdminCollegesSlugCollectionRoute._addFileChildren(
    AdminCollegesSlugCollectionRouteChildren,
  )

interface AdminCollegesSlugRouteChildren {
  AdminCollegesSlugCollectionRoute: typeof AdminCollegesSlugCollectionRouteWithChildren
  AdminCollegesSlugProductsRoute: typeof AdminCollegesSlugProductsRoute
  AdminCollegesSlugStructureRoute: typeof AdminCollegesSlugStructureRoute
  AdminCollegesSlugIndexRoute: typeof AdminCollegesSlugIndexRoute
}

const AdminCollegesSlugRouteChildren: AdminCollegesSlugRouteChildren = {
  AdminCollegesSlugCollectionRoute:
    AdminCollegesSlugCollectionRouteWithChildren,
  AdminCollegesSlugProductsRoute: AdminCollegesSlugProductsRoute,
  AdminCollegesSlugStructureRoute: AdminCollegesSlugStructureRoute,
  AdminCollegesSlugIndexRoute: AdminCollegesSlugIndexRoute,
}

const AdminCollegesSlugRouteWithChildren =
  AdminCollegesSlugRoute._addFileChildren(AdminCollegesSlugRouteChildren)

interface AdminCollegesRouteChildren {
  AdminCollegesSlugRoute: typeof AdminCollegesSlugRouteWithChildren
  AdminCollegesIndexRoute: typeof AdminCollegesIndexRoute
}

const AdminCollegesRouteChildren: AdminCollegesRouteChildren = {
  AdminCollegesSlugRoute: AdminCollegesSlugRouteWithChildren,
  AdminCollegesIndexRoute: AdminCollegesIndexRoute,
}

const AdminCollegesRouteWithChildren = AdminCollegesRoute._addFileChildren(
  AdminCollegesRouteChildren,
)

interface AdminProductMappingSizingRouteChildren {
  AdminProductMappingSizingIdRoute: typeof AdminProductMappingSizingIdRoute
  AdminProductMappingSizingIndexRoute: typeof AdminProductMappingSizingIndexRoute
}

const AdminProductMappingSizingRouteChildren: AdminProductMappingSizingRouteChildren =
  {
    AdminProductMappingSizingIdRoute: AdminProductMappingSizingIdRoute,
    AdminProductMappingSizingIndexRoute: AdminProductMappingSizingIndexRoute,
  }

const AdminProductMappingSizingRouteWithChildren =
  AdminProductMappingSizingRoute._addFileChildren(
    AdminProductMappingSizingRouteChildren,
  )

interface AdminProductMappingRouteChildren {
  AdminProductMappingDeliveryChargesRoute: typeof AdminProductMappingDeliveryChargesRoute
  AdminProductMappingSizingRoute: typeof AdminProductMappingSizingRouteWithChildren
  AdminProductMappingIndexRoute: typeof AdminProductMappingIndexRoute
}

const AdminProductMappingRouteChildren: AdminProductMappingRouteChildren = {
  AdminProductMappingDeliveryChargesRoute:
    AdminProductMappingDeliveryChargesRoute,
  AdminProductMappingSizingRoute: AdminProductMappingSizingRouteWithChildren,
  AdminProductMappingIndexRoute: AdminProductMappingIndexRoute,
}

const AdminProductMappingRouteWithChildren =
  AdminProductMappingRoute._addFileChildren(AdminProductMappingRouteChildren)

interface AdminSchoolUniformSlugCollectionRouteChildren {
  AdminSchoolUniformSlugCollectionCategoryIdRoute: typeof AdminSchoolUniformSlugCollectionCategoryIdRoute
  AdminSchoolUniformSlugCollectionIndexRoute: typeof AdminSchoolUniformSlugCollectionIndexRoute
}

const AdminSchoolUniformSlugCollectionRouteChildren: AdminSchoolUniformSlugCollectionRouteChildren =
  {
    AdminSchoolUniformSlugCollectionCategoryIdRoute:
      AdminSchoolUniformSlugCollectionCategoryIdRoute,
    AdminSchoolUniformSlugCollectionIndexRoute:
      AdminSchoolUniformSlugCollectionIndexRoute,
  }

const AdminSchoolUniformSlugCollectionRouteWithChildren =
  AdminSchoolUniformSlugCollectionRoute._addFileChildren(
    AdminSchoolUniformSlugCollectionRouteChildren,
  )

interface AdminSchoolUniformSlugRouteChildren {
  AdminSchoolUniformSlugCollectionRoute: typeof AdminSchoolUniformSlugCollectionRouteWithChildren
  AdminSchoolUniformSlugProductsRoute: typeof AdminSchoolUniformSlugProductsRoute
  AdminSchoolUniformSlugStructureRoute: typeof AdminSchoolUniformSlugStructureRoute
  AdminSchoolUniformSlugIndexRoute: typeof AdminSchoolUniformSlugIndexRoute
}

const AdminSchoolUniformSlugRouteChildren: AdminSchoolUniformSlugRouteChildren =
  {
    AdminSchoolUniformSlugCollectionRoute:
      AdminSchoolUniformSlugCollectionRouteWithChildren,
    AdminSchoolUniformSlugProductsRoute: AdminSchoolUniformSlugProductsRoute,
    AdminSchoolUniformSlugStructureRoute: AdminSchoolUniformSlugStructureRoute,
    AdminSchoolUniformSlugIndexRoute: AdminSchoolUniformSlugIndexRoute,
  }

const AdminSchoolUniformSlugRouteWithChildren =
  AdminSchoolUniformSlugRoute._addFileChildren(
    AdminSchoolUniformSlugRouteChildren,
  )

interface AdminSchoolUniformRouteChildren {
  AdminSchoolUniformSlugRoute: typeof AdminSchoolUniformSlugRouteWithChildren
  AdminSchoolUniformIndexRoute: typeof AdminSchoolUniformIndexRoute
}

const AdminSchoolUniformRouteChildren: AdminSchoolUniformRouteChildren = {
  AdminSchoolUniformSlugRoute: AdminSchoolUniformSlugRouteWithChildren,
  AdminSchoolUniformIndexRoute: AdminSchoolUniformIndexRoute,
}

const AdminSchoolUniformRouteWithChildren =
  AdminSchoolUniformRoute._addFileChildren(AdminSchoolUniformRouteChildren)

interface AdminWebsiteSettingRouteChildren {
  AdminWebsiteSettingAdvertisementsRoute: typeof AdminWebsiteSettingAdvertisementsRoute
  AdminWebsiteSettingBankAccountsRoute: typeof AdminWebsiteSettingBankAccountsRoute
  AdminWebsiteSettingBusinessInformationRoute: typeof AdminWebsiteSettingBusinessInformationRoute
  AdminWebsiteSettingIndexRoute: typeof AdminWebsiteSettingIndexRoute
}

const AdminWebsiteSettingRouteChildren: AdminWebsiteSettingRouteChildren = {
  AdminWebsiteSettingAdvertisementsRoute:
    AdminWebsiteSettingAdvertisementsRoute,
  AdminWebsiteSettingBankAccountsRoute: AdminWebsiteSettingBankAccountsRoute,
  AdminWebsiteSettingBusinessInformationRoute:
    AdminWebsiteSettingBusinessInformationRoute,
  AdminWebsiteSettingIndexRoute: AdminWebsiteSettingIndexRoute,
}

const AdminWebsiteSettingRouteWithChildren =
  AdminWebsiteSettingRoute._addFileChildren(AdminWebsiteSettingRouteChildren)

interface AdminRouteChildren {
  AdminAccessoriesRoute: typeof AdminAccessoriesRouteWithChildren
  AdminCollegesRoute: typeof AdminCollegesRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMedicalRoute: typeof AdminMedicalRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductMappingRoute: typeof AdminProductMappingRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSchoolUniformRoute: typeof AdminSchoolUniformRouteWithChildren
  AdminWebsiteSettingRoute: typeof AdminWebsiteSettingRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessoriesRoute: AdminAccessoriesRouteWithChildren,
  AdminCollegesRoute: AdminCollegesRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMedicalRoute: AdminMedicalRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductMappingRoute: AdminProductMappingRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSchoolUniformRoute: AdminSchoolUniformRouteWithChildren,
  AdminWebsiteSettingRoute: AdminWebsiteSettingRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollegesRoute: CollegesRoute,
  ContactRoute: ContactRoute,
  MedicalRoute: MedicalRoute,
  OrdersRoute: OrdersRouteWithChildren,
  SchoolUniformsRoute: SchoolUniformsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  ProductAccessoriesIdRoute: ProductAccessoriesIdRoute,
  ProductCollegeIdRoute: ProductCollegeIdRoute,
  ProductMedicalIdRoute: ProductMedicalIdRoute,
  ProductSchoolIdRoute: ProductSchoolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
